apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  interval: 5m
  chart:
    version: 8.0.9
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
    interval: 1m
  wait: false
  timeout: 5m
  url: https://helm.min.io 
  # Reference values at
  # https://github.com/minio/charts/blob/master/minio/values.yaml
  values: 
    image: 
      repository: minio/minio
      tag: RELEASE.2020-11-06T23-17-07Z
    mcImage:
      repository: minio/mc
      tag: RELEASE.2020-10-03T02-54-56Z
